ocr_dict:
  - "0"
  - "1"
  - "2"
  - "3"
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
  - A
  - B
  - C
  - D
  - E
  - F
  - G
  - H
  - J
  - K
  - L
  - M
  - N
  - P
  - Q
  - R
  - S
  - T
  - U
  - V
  - W
  - X
  - Y
  - Z
  - 京
  - 沪
  - 津
  - 渝
  - 冀
  - 晋
  - 蒙
  - 辽
  - 吉
  - 黑
  - 苏
  - 浙
  - 皖
  - 闽
  - 赣
  - 鲁
  - 豫
  - 鄂
  - 湘
  - 粤
  - 桂
  - 琼
  - 川
  - 贵
  - 云
  - 藏
  - 陕
  - 甘
  - 青
  - 宁
  - 新
  - 学
  - 警
  - 使
  - 领
  - 港
  - 澳
  - 挂
  - 临
  - 时
  - 入
  - 境
  - 民
  - 航
  - 危
  - 险
  - 品
  - 应
  - 急

color_dict:
  0: black
  1: blue
  2: green
  3: white
  4: yellow

layer_dict:
  0: single
  1: double